dist: trusty
os: linux
language: rust
rust:
  - nightly
  # Not building on stable due to nightly features, however it's a nice to have
  # - stable

env:
  global:
    # incremtal is good actually - CARGO_INCREMENTAL=0 # Incremental compilation is slower and bloats the travis cache
    - RUST_BACKTRACE=1

jobs:
  allow_failures:
    # Not building on stable due to nightly features, however it's a nice to have
    # - rust: stable
    - name: cargo clippy
  fast_finish: true
  include:
    - stage: Build
      name: cargo check
      script: cargo check
    - script: cargo clippy
      name: cargo clippy
      rust: nightly-2020-01-17
      before_script: rustup component add clippy --toolchain=$TRAVIS_RUST_VERSION || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
    - stage: Github Release
      name: cargo build --release
      script: cargo build --release
      if: tag IS present
      before_deploy:
        - npm install @sentry/cli
        - export SENTRY_ORG=myself-0q
        - export SENTRY_PROJECT=arzte-cute-bot
        - export VERSION=`./node_modules/.bin/sentry-cli releases propose-version`
        - ./node_modules/.bin/sentry-cli releases new "$VERSION"
        - cargo install --force blake2_bin
        - sh ci/before_deploy.sh
      deploy:
        token: $GITHUB_TOKEN
        file_glob: true
        file: arzte-$TRAVIS_TAG.*
        on:
          tags: true
        provider: releases
        skip_cleanup: true

after_deploy:
  - ./node_modules/.bin/sentry-cli releases finalize "$VERSION"

# Cache cargo symbols for faster build
cache: cargo

before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo
  # Remove unneeded cargo symbols for faster cache
  - cargo install --force --git https://github.com/matthiaskrgr/cargo-cache --no-default-features --features ci-autoclean cargo-cache
  - cargo-cache

before_script:
  - export PATH=$HOME/.cargo/bin:$PATH
# Disabling these for now as I'm not installing anything else, so this is pointless wasted CI time building this.
# (diesel might be a reason that I'd want this later one)
#  - cargo install cargo-update || echo "cargo-update already installed"
#  - cargo install-update -a # update outdated cached binaries

notifications:
  email: false
