dist: trusty
os: linux
language: rust
rust: nightly

jobs:
  # Not building on stable due to nightly features, however it's a nice to have
  allow_failures:
    - rust: stable
  fast_finish: true
  include:
    - stage: Check
      script: cargo check
      script: cargo clippy
    - stage: Github Release
      script: cargo build --release
      if: tag IS present
      before_deploy:
        - npm install @sentry/cli
        - export SENTRY_ORG=myself-0q
        - export SENTRY_PROJECT=arzte-cute-bot
        - export VERSION=`./node_modules/.bin/sentry-cli releases propose-version`
        - ./node_modules/.bin/sentry-cli releases new "$VERSION"
        - sh ci/before_deploy.sh
      deploy:
        token: $GITHUB_TOKEN
        file_glob: true
        file: arzte-$TRAVIS_TAG.*
        on:
          condition: $TRAVIS_RUST_VERSION = nightly
        provider: releases
        skip_cleanup: true

after_deploy:
  - ./node_modules/.bin/sentry-cli releases finalize "$VERSION"

# Cache cargo symbols for faster build
cache: cargo

before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

before_script:
  - export PATH=$HOME/.cargo/bin:$PATH
# Disabling these for now as I'm not installing anything else, so this is pointless wasted CI time building this.
# (diesel might be a reason that I'd want this later one)
#  - cargo install cargo-update || echo "cargo-update already installed"
#  - cargo install-update -a # update outdated cached binaries

notifications:
  email: false
