[package]
name = "arzte-bot"
version = "0.1.0"
authors = ["Faey Hoffmeyer <hoffmeyer25@gmail.com>"]

[dependencies]
serenity = "0.5.10"
config = "0.9.1"
env_logger = "0.5.13"
kankyo = "0.2.0"
log = "0.4.6"
rand = "0.5.5"
chrono = "0.4.6"
typemap = "0.3.3"
sys-info = "0.5.6"

[replace]
"openssl:0.9.24" = { git = "https://github.com/ishitatsuyuki/rust-openssl", branch = "0.9.x" }