[package]
name = "arzte"
version = "0.1.0"
authors = ["Faey Hoffmeyer <hoffmeyer25@gmail.com>"]
publish = false
build = "build.rs"
edition = "2018"

[dependencies]
env_logger = "0.6"
kankyo = "0.3.0"
log = "0.4"

[dependencies.serenity]
version = "0.6"
features = ["cache", "voice", "http", "framework", "standard_framework", "rustls_backend"]

[build-dependencies]
built = "0.3.1"
