[package]
name = "arzte"
version = "0.9.30"
authors = ["Iris Hoffmeyer <hoffmeyer25@gmail.com>"]
publish = false
build = "build.rs"
edition = "2018"

[dependencies]
pretty_env_logger = "0.4"
log = "0.4"
asciimath = "0.8"
config = "0.10"
chrono = "0.4"
typemap = "0.3"
sys-info = "0.5"
built = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
reqwest = "0.10"
sentry = "0.17.0" # Specfiying a full version as sentry won't follow semver until release 1.0
tar = "0.4"
flate2 = "1.0"
semver = "0.9"
blake2b_simd = "0.5"

[dependencies.serenity]
version = "0.8.0"
default-features = false
features = ["cache", "http", "framework", "standard_framework", "rustls_backend"]

[build-dependencies]
built = "0.4"
