[package]
name = "arzte"
version = "0.0.1-alpha"
authors = ["Faey Hoffmeyer <hoffmeyer25@gmail.com>"]
build = "build.rs"
edition = "2018"

[dependencies]
serenity = "0.5"
config = "0.9"
env_logger = "0.5.13"
kankyo = "0.2"
log = "0.4"
rand = "0.6"
chrono = "0.4"
typemap = "0.3"
sys-info = "0.5"
built = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
reqwest = "0.9"
meval = "0.2"
sentry = "0.12.0"

[build-dependencies]
built = "0.3"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[replace]
"openssl:0.9.24" = { git = "https://github.com/ishitatsuyuki/rust-openssl", branch = "0.9.x" }